//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.Resources.Language_Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguagePack {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguagePack() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebClient.Resources.Language_Files.LanguagePack", typeof(LanguagePack).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application description page..
        /// </summary>
        public static string AboutPageDescriptionText {
            get {
                return ResourceManager.GetString("AboutPageDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this area to provide additional information..
        /// </summary>
        public static string AboutPageText {
            get {
                return ResourceManager.GetString("AboutPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ActionLabel {
            get {
                return ResourceManager.GetString("ActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string AddressCityPlaceholder {
            get {
                return ResourceManager.GetString("AddressCityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Details.
        /// </summary>
        public static string AddressDetails {
            get {
                return ResourceManager.GetString("AddressDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Information.
        /// </summary>
        public static string AddressExtraPlaceholder {
            get {
                return ResourceManager.GetString("AddressExtraPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address ID.
        /// </summary>
        public static string AddressIDPlaceholder {
            get {
                return ResourceManager.GetString("AddressIDPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string AddressNumberPlaceholder {
            get {
                return ResourceManager.GetString("AddressNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string AddressStreetPlaceholder {
            get {
                return ResourceManager.GetString("AddressStreetPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string CompaniesPlaceholder {
            get {
                return ResourceManager.GetString("CompaniesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string CompanyAddressLabel {
            get {
                return ResourceManager.GetString("CompanyAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Number.
        /// </summary>
        public static string CompanyBankNumberLabel {
            get {
                return ResourceManager.GetString("CompanyBankNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string CompanyLocationLabel {
            get {
                return ResourceManager.GetString("CompanyLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        public static string CompanyRegistrationNumberLabel {
            get {
                return ResourceManager.GetString("CompanyRegistrationNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aalborg, Denmark.
        /// </summary>
        public static string ContactPageCityAndCountry {
            get {
                return ResourceManager.GetString("ContactPageCityAndCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string ContactPagePhone {
            get {
                return ResourceManager.GetString("ContactPagePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +45 50 22 77 79.
        /// </summary>
        public static string ContactPagePhoneNumber {
            get {
                return ResourceManager.GetString("ContactPagePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofiendalsvej 60.
        /// </summary>
        public static string ContactPageStreetAndNumber {
            get {
                return ResourceManager.GetString("ContactPageStreetAndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string ContactPageSupport {
            get {
                return ResourceManager.GetString("ContactPageSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1062012@ucn.dk.
        /// </summary>
        public static string ContactPageSupportEmail {
            get {
                return ResourceManager.GetString("ContactPageSupportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Details.
        /// </summary>
        public static string CustomerDetails {
            get {
                return ResourceManager.GetString("CustomerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string CustomerEmailPlaceholder {
            get {
                return ResourceManager.GetString("CustomerEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Name.
        /// </summary>
        public static string CustomerFamilyNamePlaceholder {
            get {
                return ResourceManager.GetString("CustomerFamilyNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Name.
        /// </summary>
        public static string CustomerGivenNamePlaceholder {
            get {
                return ResourceManager.GetString("CustomerGivenNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string CustomerIdPlaceholder {
            get {
                return ResourceManager.GetString("CustomerIdPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerNamePlaceHolder {
            get {
                return ResourceManager.GetString("CustomerNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button removes item, action can be canceled by clicking button again..
        /// </summary>
        public static string DeleteButtonTitle {
            get {
                return ResourceManager.GetString("DeleteButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Number.
        /// </summary>
        public static string DocumentNumberPlaceholder {
            get {
                return ResourceManager.GetString("DocumentNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string ErrorPageText {
            get {
                return ResourceManager.GetString("ErrorPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        public static string ErrorPageTitle {
            get {
                return ResourceManager.GetString("ErrorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Time.
        /// </summary>
        public static string FinishedTimePlaceHolder {
            get {
                return ResourceManager.GetString("FinishedTimePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming.
        /// </summary>
        public static string Incoming {
            get {
                return ResourceManager.GetString("Incoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Info.
        /// </summary>
        public static string InvoiceInfoLabel {
            get {
                return ResourceManager.GetString("InvoiceInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice List.
        /// </summary>
        public static string InvoiceList {
            get {
                return ResourceManager.GetString("InvoiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for invoice.
        /// </summary>
        public static string InvoiceSearch {
            get {
                return ResourceManager.GetString("InvoiceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice type.
        /// </summary>
        public static string InvoiceType {
            get {
                return ResourceManager.GetString("InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new item.
        /// </summary>
        public static string ItemAdd {
            get {
                return ResourceManager.GetString("ItemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price With Tax.
        /// </summary>
        public static string ItemIncomingPriceLabel {
            get {
                return ResourceManager.GetString("ItemIncomingPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing price.
        /// </summary>
        public static string ItemOutgoingPriceLabel {
            get {
                return ResourceManager.GetString("ItemOutgoingPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item search.
        /// </summary>
        public static string ItemSearch {
            get {
                return ResourceManager.GetString("ItemSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Selection.
        /// </summary>
        public static string ItemSelection {
            get {
                return ResourceManager.GetString("ItemSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description.
        /// </summary>
        public static string JobDescriptionPlaceHolder {
            get {
                return ResourceManager.GetString("JobDescriptionPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Details.
        /// </summary>
        public static string JobDetails {
            get {
                return ResourceManager.GetString("JobDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Id.
        /// </summary>
        public static string JobIdPlaceHolder {
            get {
                return ResourceManager.GetString("JobIdPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job List.
        /// </summary>
        public static string JobList {
            get {
                return ResourceManager.GetString("JobList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Name.
        /// </summary>
        public static string JobNamePlaceHolder {
            get {
                return ResourceManager.GetString("JobNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job search.
        /// </summary>
        public static string JobSearchCardTitle {
            get {
                return ResourceManager.GetString("JobSearchCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Status.
        /// </summary>
        public static string JobStatus {
            get {
                return ResourceManager.GetString("JobStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string JobStatusDone {
            get {
                return ResourceManager.GetString("JobStatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Proggress.
        /// </summary>
        public static string JobStatusInProggress {
            get {
                return ResourceManager.GetString("JobStatusInProggress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned.
        /// </summary>
        public static string JobStatusUnassigned {
            get {
                return ResourceManager.GetString("JobStatusUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian.
        /// </summary>
        public static string Latvian {
            get {
                return ResourceManager.GetString("Latvian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Company.
        /// </summary>
        public static string NewCompanyButton {
            get {
                return ResourceManager.GetString("NewCompanyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Invoice.
        /// </summary>
        public static string NewInvoiceButton {
            get {
                return ResourceManager.GetString("NewInvoiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Item.
        /// </summary>
        public static string NewItemButton {
            get {
                return ResourceManager.GetString("NewItemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new job.
        /// </summary>
        public static string NewJob {
            get {
                return ResourceManager.GetString("NewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Status.
        /// </summary>
        public static string NotificationStatus {
            get {
                return ResourceManager.GetString("NotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing.
        /// </summary>
        public static string Outgoing {
            get {
                return ResourceManager.GetString("Outgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        public static string PaymentDateLabel {
            get {
                return ResourceManager.GetString("PaymentDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription Date.
        /// </summary>
        public static string PrescriptionDateLabel {
            get {
                return ResourceManager.GetString("PrescriptionDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Barcode.
        /// </summary>
        public static string ProductBarcodeLabel {
            get {
                return ResourceManager.GetString("ProductBarcodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group Margin.
        /// </summary>
        public static string ProductGroupMarginLabel {
            get {
                return ResourceManager.GetString("ProductGroupMarginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProductGroupNameLabel {
            get {
                return ResourceManager.GetString("ProductGroupNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductNameLabel {
            get {
                return ResourceManager.GetString("ProductNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Price.
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string ProductsLabel {
            get {
                return ResourceManager.GetString("ProductsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Company.
        /// </summary>
        public static string ReceiverCompanyLabel {
            get {
                return ResourceManager.GetString("ReceiverCompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving company.
        /// </summary>
        public static string ReceivingCompany {
            get {
                return ResourceManager.GetString("ReceivingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reception Date.
        /// </summary>
        public static string ReceptionDateLabel {
            get {
                return ResourceManager.GetString("ReceptionDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative Name.
        /// </summary>
        public static string RepresentativeNameLabel {
            get {
                return ResourceManager.GetString("RepresentativeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Company.
        /// </summary>
        public static string SenderCompanyLabel {
            get {
                return ResourceManager.GetString("SenderCompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending company.
        /// </summary>
        public static string SendingCompany {
            get {
                return ResourceManager.GetString("SendingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SerialNumberLabel {
            get {
                return ResourceManager.GetString("SerialNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Time.
        /// </summary>
        public static string StartedTimePlaceHolder {
            get {
                return ResourceManager.GetString("StartedTimePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Group.
        /// </summary>
        public static string TaxGroupLabel {
            get {
                return ResourceManager.GetString("TaxGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string TaxLabel {
            get {
                return ResourceManager.GetString("TaxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Cost.
        /// </summary>
        public static string TransportCostLabel {
            get {
                return ResourceManager.GetString("TransportCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contact page..
        /// </summary>
        public static string YourContectPage {
            get {
                return ResourceManager.GetString("YourContectPage", resourceCulture);
            }
        }
    }
}
