// <auto-generated />
namespace InternalApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removedDispalyNamesfromjobandcustomertables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedDispalyNamesfromjobandcustomertables));
        
        string IMigrationMetadata.Id
        {
            get { return "201812050952594_removed DispalyNames from job and customer tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
