// <auto-generated />
namespace InternalApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_JobsCustomersAddressestables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_JobsCustomersAddressestables));
        
        string IMigrationMetadata.Id
        {
            get { return "201811131153559_Added_Jobs-Customers-Addresses-tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
